name: Sync BMBF GitLab

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: update time
      run: date +"%s,%Y%m%d%H%M%S" > date_refreshed.txt && git config --local user.name "gh_runner" && git add date_refreshed.txt && git commit -m "update time"
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://git.bmbf.dev/unicorns/resources.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sync_tags: "true"
