name: Sync BMBF GitLab

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://git.bmbf.dev/unicorns/resources.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.PAT }}
        sync_tags: "true"
